version = 1

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["req.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  additional_builtins = [
    "_",
  ]
  
[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "docker"
enabled = true
