version = 1

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["req.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  additional_builtins = [
    "_",
  ]
  type_checker = "mypy"

[[analyzers]]
name = "shell"
enabled = true


[[analyzers]]
name = "terraform"
enabled = true


[[transformers]]
name = "rustfmt"
enabled = true
